# Generated by Django 3.2 on 2021-04-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=80)),
                ('location', models.CharField(default='location', max_length=80)),
                ('image', models.CharField(default='img', max_length=100)),
                ('free_school_meals', models.CharField(default='yes', max_length=20)),
                ('coronavirus_face_coverings', models.CharField(default='yes', max_length=20)),
                ('testing_of_nhs_staff', models.CharField(default='yes', max_length=20)),
                ('police_crime_sentencing', models.CharField(default='yes', max_length=20)),
                ('immigration_and_social_security', models.CharField(default='yes', max_length=20)),
                ('environment_bill', models.CharField(default='yes', max_length=20)),
                ('european_union_withdrawal', models.CharField(default='yes', max_length=20)),
                ('domestic_abuse_bill', models.CharField(default='yes', max_length=20)),
                ('nhs_pay_award', models.CharField(default='yes', max_length=20)),
                ('agriculture', models.CharField(default='yes', max_length=20)),
                ('offensive_weapons_report_nc26', models.CharField(default='yes', max_length=20)),
                ('windrush', models.CharField(default='yes', max_length=20)),
                ('unaccompanied_children', models.CharField(default='yes', max_length=20)),
                ('trade_bill', models.CharField(default='yes', max_length=20)),
                ('financial_assitance_to_industry', models.CharField(default='yes', max_length=20)),
                ('health_protection', models.CharField(default='yes', max_length=20)),
                ('brexit_air_quality', models.CharField(default='yes', max_length=20)),
                ('combating_violence_against_women', models.CharField(default='yes', max_length=20)),
                ('relationships_sex_education', models.CharField(default='yes', max_length=20)),
                ('brexit_rural_economy', models.CharField(default='yes', max_length=20)),
                ('party', models.ManyToManyField(related_name='mp', to='party.party')),
            ],
        ),
    ]
