# Generated by Django 3.2 on 2021-04-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mp',
            name='agriculture',
            field=models.CharField(default='yes', max_length=20),
        ),
        migrations.AddField(
            model_name='mp',
            name='brexit_air_quality',
            field=models.CharField(default='yes', max_length=20),
        ),
        migrations.AddField(
            model_name='mp',
            name='brexit_rural_economy',
            field=models.CharField(default='yes', max_length=20),
        ),
        migrations.AddField(
            model_name='mp',
            name='combating_violence_against_women',
            field=models.CharField(default='yes', max_length=20),
        ),
        migrations.AddField(
            model_name='mp',
            name='coronavirus_face_coverings',
            field=models.CharField(default='yes', max_length=20),
        ),
        migrations.AddField(
            model_name='mp',
            name='domestic_abuse_bill',
            field=models.CharField(default='yes', max_length=20),
        ),
        migrations.AddField(
            model_name='mp',
            name='environment_bill',
            field=models.CharField(default='yes', max_length=20),
        ),
        migrations.AddField(
            model_name='mp',
            name='european_union_withdrawal',
            field=models.CharField(default='yes', max_length=20),
        ),
        migrations.AddField(
            model_name='mp',
            name='financial_assitance_to_industry',
            field=models.CharField(default='yes', max_length=20),
        ),
        migrations.AddField(
            model_name='mp',
            name='free_school_meals',
            field=models.CharField(default='yes', max_length=20),
        ),
        migrations.AddField(
            model_name='mp',
            name='health_protection',
            field=models.CharField(default='yes', max_length=20),
        ),
        migrations.AddField(
            model_name='mp',
            name='immigration_and_social_security',
            field=models.CharField(default='yes', max_length=20),
        ),
        migrations.AddField(
            model_name='mp',
            name='nhs_pay_award',
            field=models.CharField(default='yes', max_length=20),
        ),
        migrations.AddField(
            model_name='mp',
            name='offensive_weapons_report_nc26',
            field=models.CharField(default='yes', max_length=20),
        ),
        migrations.AddField(
            model_name='mp',
            name='police_crime_sentencing',
            field=models.CharField(default='yes', max_length=20),
        ),
        migrations.AddField(
            model_name='mp',
            name='relationships_sex_education',
            field=models.CharField(default='yes', max_length=20),
        ),
        migrations.AddField(
            model_name='mp',
            name='testing_of_nhs_staff',
            field=models.CharField(default='yes', max_length=20),
        ),
        migrations.AddField(
            model_name='mp',
            name='trade_bill',
            field=models.CharField(default='yes', max_length=20),
        ),
        migrations.AddField(
            model_name='mp',
            name='unaccompanied_children',
            field=models.CharField(default='yes', max_length=20),
        ),
        migrations.AddField(
            model_name='mp',
            name='windrush',
            field=models.CharField(default='yes', max_length=20),
        ),
        migrations.AlterField(
            model_name='mp',
            name='image',
            field=models.CharField(default='img', max_length=100),
        ),
        migrations.AlterField(
            model_name='mp',
            name='location',
            field=models.CharField(default='location', max_length=80),
        ),
        migrations.AlterField(
            model_name='mp',
            name='name',
            field=models.CharField(default='name', max_length=80),
        ),
    ]
