# Generated by Django 3.2 on 2021-04-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
        ('mp', '0002_auto_20210414_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='mp',
            name='party',
            field=models.ManyToManyField(related_name='mp', to='party.party'),
        ),
    ]
