# Generated by Django 3.2 on 2021-04-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.CharField(default='image.jpeg', max_length=300),
        ),
    ]
